#include "stdafx.h"
#include "chart.h"


Chart::mapNewZealand():
	mapNewZealand_
	{
		{ mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kNorthland, mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kBayOfIslands, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kCoromandel,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kWater, mapNewZealand::kBayOfPlenty },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kLand, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kLand, mapNewZealand::kLand,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater },
		{ mapNewZealand::kWater,  mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater,  mapNewZealand::kWater, mapNewZealand::kWater, mapNewZealand::kWater }

	}
